#==========================================================
# Database connection properties
#==========================================================
database_host=localhost
database_name=parts_db1
database_user=lab
database_pass=USE_my.cnf

#==========================================================
# PartKeepr web paths
#==========================================================
partkeepr_data_path=/var/www/PartKeepr/data
partkeepr_config_path=/var/www/PartKeepr/app/config

#==========================================================
# Backup storage location
#==========================================================
backup_root_path=/mnt/hgfs/Share/backups

#==========================================================
# Data retention period (in days)
#==========================================================
data_retention_period=2
